// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByPTYiUxQpnp_V_yGxSeT8YwGzmvQ1XrE',
    appId: '1:650150341329:web:1a4e577228781b96e473f0',
    messagingSenderId: '650150341329',
    projectId: 'sound-classifier-c618b',
    authDomain: 'sound-classifier-c618b.firebaseapp.com',
    storageBucket: 'sound-classifier-c618b.firebasestorage.app',
    measurementId: 'G-0ST502EBQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz6KnA9G_LtokV3uaVyUp5MtXYBAado9s',
    appId: '1:650150341329:android:6230f05fda5735bde473f0',
    messagingSenderId: '650150341329',
    projectId: 'sound-classifier-c618b',
    storageBucket: 'sound-classifier-c618b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR4Dw2jIlyKecHAeOg4mDnWk5B_vTSrD8',
    appId: '1:650150341329:ios:780c71132351e7efe473f0',
    messagingSenderId: '650150341329',
    projectId: 'sound-classifier-c618b',
    storageBucket: 'sound-classifier-c618b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR4Dw2jIlyKecHAeOg4mDnWk5B_vTSrD8',
    appId: '1:650150341329:ios:780c71132351e7efe473f0',
    messagingSenderId: '650150341329',
    projectId: 'sound-classifier-c618b',
    storageBucket: 'sound-classifier-c618b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByPTYiUxQpnp_V_yGxSeT8YwGzmvQ1XrE',
    appId: '1:650150341329:web:6eef7def0a7edef7e473f0',
    messagingSenderId: '650150341329',
    projectId: 'sound-classifier-c618b',
    authDomain: 'sound-classifier-c618b.firebaseapp.com',
    storageBucket: 'sound-classifier-c618b.firebasestorage.app',
    measurementId: 'G-00Z97JC4H3',
  );
}
